#====================================================
# spring boot配置
#
# 完整文档：
#====================================================

spring:
  profiles:
    # 测试dev 生产prod
    active: dev
  # active: prod
  application:
    name: bill
  # 默认时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    inetutils:
      default-ip-address: 39.98.50.149
  #spring redis
  redis:
    host: 39.98.50.149
    port: 6379
    password: aliyunr1!
    timeout: 1000
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 500
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 1000
      # 连接池中的最大空闲连接
      max-idle: 100
      min-idle: 10

# 微服务注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:root@39.98.50.149:10000/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: ${spring.cloud.inetutils.default-ip-address}
    ip-address: ${spring.cloud.inetutils.default-ip-address}
    prefer-ip-address: true
    instance-id: ${spring.cloud.inetutils.default-ip-address}:${server.port}

# 停止服务
endpoints:
  shutdown:
    #开启shutdown端点
    enabled: true
    path: stop
management:
  security:
    #是否启用安全
    enabled: true
  port: 10003
  address: 127.0.0.1

server:
  port: 10003
  tomcat:
    uri-encoding: utf-8

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.user.model.entity
  #开启驼峰命名转换
  configuration:
      map-underscore-to-camel-case: true

# mybatis分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# swagger
swagger2:
    package: com.bill.controller
